services:
  - type: web
    name: ciphertech-url-shortener
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
